# Generated by Django 4.0.4 on 2022-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default='0')),
                ('highscore', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.SmallIntegerField(default=1)),
                ('text', models.CharField(max_length=300)),
                ('points', models.FloatField(default=0)),
                ('answer1', models.CharField(max_length=50)),
                ('answer2', models.CharField(max_length=50)),
                ('answer3', models.CharField(max_length=50)),
                ('answer4', models.CharField(max_length=50)),
                ('called', models.BooleanField(default='False')),
            ],
        ),
    ]
